# Generated by Django 4.1.6 on 2023-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_alter_request_spare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-time_create'], 'verbose_name': 'запрос', 'verbose_name_plural': 'запросы'},
        ),
        migrations.AddConstraint(
            model_name='auto',
            constraint=models.CheckConstraint(check=models.Q(('vin__iregex', '[a-zA-Z0-9]{17}')), name='длина VIN-номера 17 символов', violation_error_message='длина VIN-номера должна быть 17 символов'),
        ),
    ]
