# Generated by Django 4.1.6 on 2023-03-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_alter_auto_vin_alter_spare_autodoc_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='price_graph',
            field=models.ImageField(null=True, upload_to='graphs', verbose_name='график изменения цен'),
        ),
    ]
