# Generated by Django 4.1.7 on 2023-04-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0008_request_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='autos.spare', verbose_name='запчасть'),
        ),
    ]
