# Generated by Django 4.1.7 on 2024-04-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0009_alter_request_spare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='delivery_time',
            field=models.IntegerField(verbose_name='срок доставки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='difference',
            field=models.IntegerField(default=0, verbose_name='отличие от предыдущей цены'),
        ),
        migrations.AlterField(
            model_name='request',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
