services:
  web-app:
    container_name: web-app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./autoworld:/autoworld
    env_file:
      - .env
    command: >
      sh -c "gunicorn autoworld.wsgi:application --bind 0.0.0.0:8000 --workers 4 --reload"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:14.6
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["-c", "log_timezone=Asia/Krasnoyarsk"]
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    hostname: redis
    env_file:
      - .env

  worker:
    container_name: worker
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./autoworld:/autoworld
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - .env

  beat:
    container_name: beat
    build:
      context: .
    hostname: beat
    entrypoint: celery
    command: -A celery_app.app beat --loglevel=info
    volumes:
      - ./autoworld:/autoworld
    links:
      - redis
    depends_on:
      - worker
    env_file:
      - .env

  flower:
    container_name: flower
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./autoworld:/autoworld
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
    name: pgdata