# Generated by Django 4.1.6 on 2023-02-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='autos.spare', verbose_name='запчасть'),
        ),
    ]
