# Generated by Django 4.1.6 on 2023-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='autodoc_URL',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='ссылка на Autodoc'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='exist_URL',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='ссылка на Exist'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='partnumber',
            field=models.CharField(max_length=100, unique=True, verbose_name='артикул'),
        ),
    ]
