# Generated by Django 4.1.7 on 2023-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_spare_price_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='price_graph',
            field=models.ImageField(blank=True, null=True, upload_to='graphs', verbose_name='график изменения цен'),
        ),
    ]
