name: Deploy to server

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and run commands on the remote server
        run: |
          ssh -p ${{ secrets.SSH_PORT_OF_HOST }} ${{ secrets.USER_OF_HOST }}@${{ secrets.IP_ADDRESS_OF_HOST }}
      - name: Env activate
        run: |
          source ~/venv/bin/activate
      - name: Git pull
        run: |
          git pull
      - name: Update requirements
        run: |
          pip install -r ~/django_auto/requirements.txt
      - name: Services restart
        run: |
          sudo supervisorctl restart auto celery celerybeat
